---
# tasks file for initial

- name: usuarios padrao
  include: user.yaml

- name: pacatos para debian
  include: debian.yaml
  when: ansible_os_family == "Debian"

- name: pacotes para centos
  include: centos.yaml
  when: ansible_os_family == "RedHat"

