---

- name: Install Docker-CE
  hosts: docker
  tasks:
   - name: fazendo download script geralzao do Docker
     shell: 'curl -fsSL https://get.docker.com -o get-docker.sh'

   - name: Install Docker
     shell: 'sh get-docker.sh'

